# drafter/pdf_generator.py
# Generates strictly formal A4 PDF — court document style
# No emoji, no color highlights in body, professional typography

import io
import re
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch, cm
from reportlab.pdfgen import canvas
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from drafter.document_types import DOCUMENT_TYPES

# All documents use same formal black/navy color scheme
FORMAL_HEADER_COLOR = colors.HexColor('#1a1a2e')   # deep navy
FORMAL_RULE_COLOR   = colors.HexColor('#000000')   # black rule lines
FORMAL_TEXT_COLOR   = colors.HexColor('#1a1a1a')   # near black
FORMAL_META_COLOR   = colors.HexColor('#333333')   # dark grey


class PageNumberCanvas(canvas.Canvas):
    """Adds page numbers and formal footer to every page."""

    def __init__(self, *args, **kwargs):
        canvas.Canvas.__init__(self, *args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self._draw_footer(total)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def _draw_footer(self, total_pages):
        # Bottom footer line
        self.setStrokeColor(colors.HexColor('#000000'))
        self.setLineWidth(0.5)
        self.line(
            0.9 * inch,
            0.65 * inch,
            A4[0] - 0.9 * inch,
            0.65 * inch
        )

        self.setFont("Helvetica", 7)
        self.setFillColor(colors.HexColor('#444444'))

        # Left: document title
        self.drawString(
            0.9 * inch,
            0.48 * inch,
            "GENERATED BY LEGAL AI RAG SYSTEM — "
            "FOR REFERENCE ONLY — VERIFY WITH QUALIFIED ADVOCATE"
        )
        # Right: page number
        self.drawRightString(
            A4[0] - 0.9 * inch,
            0.48 * inch,
            f"Page {self._pageNumber} of {total_pages}"
        )


def generate_pdf(
    document_type: str,
    document_text: str,
    extracted_fields: dict,
) -> bytes:
    """
    Generates a strictly formal court-style A4 PDF.
    Black and white. No emoji. No color highlights in body.
    Professional legal typography throughout.
    """
    buffer = io.BytesIO()
    config = DOCUMENT_TYPES[document_type]
    today  = datetime.today().strftime("%d %B %Y")

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=1.0 * inch,
        leftMargin=1.0 * inch,
        topMargin=1.1 * inch,
        bottomMargin=1.0 * inch,
        title=document_type,
        author="Legal AI RAG System",
        subject=config['full_name'],
    )

    styles = getSampleStyleSheet()

    # ── Typography — formal legal document styles ──────────────────────

    main_title_style = ParagraphStyle(
        'MainTitle',
        fontSize=14,
        alignment=TA_CENTER,
        textColor=FORMAL_HEADER_COLOR,
        fontName='Helvetica-Bold',
        spaceAfter=4,
        spaceBefore=0,
        leading=18,
    )
    subtitle_style = ParagraphStyle(
        'Subtitle',
        fontSize=10,
        alignment=TA_CENTER,
        textColor=FORMAL_HEADER_COLOR,
        fontName='Helvetica',
        spaceAfter=2,
        leading=14,
    )
    act_ref_style = ParagraphStyle(
        'ActRef',
        fontSize=8,
        alignment=TA_CENTER,
        textColor=colors.HexColor('#444444'),
        fontName='Helvetica-Oblique',
        spaceAfter=6,
        leading=12,
    )
    confidential_style = ParagraphStyle(
        'Confidential',
        fontSize=8,
        alignment=TA_CENTER,
        textColor=FORMAL_HEADER_COLOR,
        fontName='Helvetica-Bold',
        spaceAfter=10,
        leading=12,
    )
    section_heading_style = ParagraphStyle(
        'SectionHeading',
        fontSize=9,
        textColor=FORMAL_HEADER_COLOR,
        fontName='Helvetica-Bold',
        spaceBefore=10,
        spaceAfter=4,
        leading=13,
    )
    body_style = ParagraphStyle(
        'Body',
        fontSize=9.5,
        leading=16,
        alignment=TA_JUSTIFY,
        textColor=FORMAL_TEXT_COLOR,
        fontName='Helvetica',
        spaceAfter=4,
        firstLineIndent=0,
    )
    numbered_para_style = ParagraphStyle(
        'NumberedPara',
        fontSize=9.5,
        leading=16,
        alignment=TA_JUSTIFY,
        textColor=FORMAL_TEXT_COLOR,
        fontName='Helvetica',
        spaceAfter=5,
        leftIndent=18,
        firstLineIndent=-18,
    )
    field_label_style = ParagraphStyle(
        'FieldLabel',
        fontSize=8.5,
        textColor=FORMAL_HEADER_COLOR,
        fontName='Helvetica-Bold',
        leading=12,
    )
    field_value_style = ParagraphStyle(
        'FieldValue',
        fontSize=8.5,
        textColor=FORMAL_TEXT_COLOR,
        fontName='Helvetica',
        leading=12,
    )
    disclaimer_style = ParagraphStyle(
        'Disclaimer',
        fontSize=7,
        alignment=TA_CENTER,
        textColor=colors.HexColor('#666666'),
        fontName='Helvetica-Oblique',
        spaceBefore=14,
        leading=11,
    )

    story = []

    # ── HEADER ────────────────────────────────────────────────────────

    story.append(HRFlowable(
        width="100%",
        thickness=2,
        color=FORMAL_HEADER_COLOR,
        spaceAfter=10,
    ))

    story.append(Paragraph(
        document_type.upper(),
        main_title_style
    ))
    story.append(Paragraph(
        config['full_name'].upper(),
        subtitle_style
    ))
    story.append(Paragraph(
        f"Under: {config['act']}",
        act_ref_style
    ))
    story.append(Paragraph(
        "WITHOUT PREJUDICE     |     PRIVATE AND CONFIDENTIAL",
        confidential_style
    ))

    story.append(HRFlowable(
        width="100%",
        thickness=1,
        color=FORMAL_HEADER_COLOR,
        spaceAfter=10,
    ))

    # ── METADATA TABLE ────────────────────────────────────────────────

    urgency = extracted_fields.get('urgency_level', 'MEDIUM').upper()
    meta_data = [
        ["Date of Draft",    today],
        ["Document Type",    config['full_name']],
        ["Submit To",        config['authority']],
        ["Urgency Level",    urgency],
    ]
    meta_table = Table(meta_data, colWidths=[1.8*inch, 5.2*inch])
    meta_table.setStyle(TableStyle([
        ('FONTNAME',     (0, 0), (0, -1), 'Helvetica-Bold'),
        ('FONTNAME',     (1, 0), (1, -1), 'Helvetica'),
        ('FONTSIZE',     (0, 0), (-1, -1), 8.5),
        ('TEXTCOLOR',    (0, 0), (0, -1), FORMAL_HEADER_COLOR),
        ('TEXTCOLOR',    (1, 0), (1, -1), FORMAL_TEXT_COLOR),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [
            colors.HexColor('#f0f0f0'),
            colors.white
        ]),
        ('GRID',         (0, 0), (-1, -1), 0.3, colors.HexColor('#cccccc')),
        ('PADDING',      (0, 0), (-1, -1), 5),
        ('VALIGN',       (0, 0), (-1, -1), 'TOP'),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 0.12 * inch))

    story.append(HRFlowable(
        width="100%",
        thickness=0.5,
        color=colors.HexColor('#999999'),
        spaceAfter=10,
    ))

    # ── DOCUMENT BODY ─────────────────────────────────────────────────

    for line in document_text.split('\n'):
        line = line.strip()

        if not line:
            story.append(Spacer(1, 3))
            continue

        # Remove any accidental emoji (post-processing safety net)
        line = re.sub(
            u'[\U00010000-\U0010ffff]|'
            u'[\u2600-\u26FF]|[\u2700-\u27BF]',
            '', line
        )
        line = line.strip()
        if not line:
            continue

        # Remove markdown artifacts
        line = re.sub(r'\*{1,3}([^*]+)\*{1,3}', r'\1', line)
        line = re.sub(r'#{1,6}\s+', '', line)

        # Escape XML special characters for ReportLab
        line = line.replace('&', '&amp;')
        line = line.replace('<', '&lt;')
        line = line.replace('>', '&gt;')

        # Classify line type
        is_major_divider = line.startswith('---') or line.startswith('===')
        is_all_caps_heading = (
            line.isupper() and
            3 < len(line) < 80 and
            not any(c.isdigit() for c in line[:2])
        )
        is_part_heading = (
            line.upper().startswith('PART ') or
            line.upper().startswith('SECTION ')
        )
        is_numbered = (
            len(line) > 3 and
            line[0].isdigit() and
            line[1] in '.)'
        )
        is_that_clause = line.upper().startswith('THAT ')
        is_signature_block = any(
            line.startswith(w) for w in [
                'Signature', 'Name (in full)', 'Date  :', 'Date:',
                'Place :', 'Place:', 'Yours faithfully',
                'Yours sincerely', 'FOR OFFICE USE',
                'ENCLOSURES', 'Enclosures',
            ]
        )
        is_field_line = ':' in line and len(line) < 70 and not is_that_clause

        if is_major_divider:
            story.append(HRFlowable(
                width="100%",
                thickness=0.3,
                color=colors.HexColor('#aaaaaa'),
                spaceBefore=4,
                spaceAfter=4,
            ))

        elif is_all_caps_heading or is_part_heading:
            story.append(Spacer(1, 5))
            story.append(Paragraph(line, section_heading_style))

        elif is_numbered:
            story.append(Paragraph(line, numbered_para_style))

        elif is_that_clause:
            story.append(Spacer(1, 3))
            story.append(Paragraph(line, body_style))

        elif is_signature_block:
            story.append(Spacer(1, 5))
            story.append(Paragraph(line, body_style))

        elif is_field_line:
            # Format as two-column field: label | value
            parts = line.split(':', 1)
            if len(parts) == 2:
                label = parts[0].strip() + ' :'
                value = parts[1].strip() if parts[1].strip() else '________________'
                field_row = [[
                    Paragraph(label, field_label_style),
                    Paragraph(value, field_value_style)
                ]]
                field_table = Table(field_row, colWidths=[2.0*inch, 4.8*inch])
                field_table.setStyle(TableStyle([
                    ('VALIGN',   (0, 0), (-1, -1), 'TOP'),
                    ('PADDING',  (0, 0), (-1, -1), 2),
                    ('LEFTPADDING', (0, 0), (0, -1), 0),
                ]))
                story.append(field_table)
            else:
                story.append(Paragraph(line, body_style))

        else:
            story.append(Paragraph(line, body_style))

    # ── APPLICABLE SECTIONS ───────────────────────────────────────────

    story.append(Spacer(1, 0.1 * inch))
    story.append(HRFlowable(
        width="100%",
        thickness=1,
        color=FORMAL_HEADER_COLOR,
        spaceAfter=8,
    ))
    story.append(Paragraph(
        "APPLICABLE LEGAL PROVISIONS",
        section_heading_style
    ))

    applicable = extracted_fields.get('applicable_sections', [])
    sections_text = (
        "  |  ".join(applicable)
        if isinstance(applicable, list) and applicable
        else str(applicable) if applicable
        else "As cited in document above"
    )
    story.append(Paragraph(sections_text, body_style))

    # ── DISCLAIMER ────────────────────────────────────────────────────

    story.append(HRFlowable(
        width="100%",
        thickness=0.5,
        color=colors.HexColor('#999999'),
        spaceBefore=10,
        spaceAfter=4,
    ))
    story.append(Paragraph(
        "DISCLAIMER: This document has been generated by an artificial "
        "intelligence system for drafting assistance and reference purposes "
        "only. It does not constitute legal advice. The user is advised to "
        "review this document with a qualified and enrolled advocate before "
        "submission to any authority. All applicable law section numbers "
        "must be independently verified before filing.",
        disclaimer_style
    ))

    doc.build(story, canvasmaker=PageNumberCanvas)
    return buffer.getvalue()
